name: sistem_rs
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4
  
dependencies:
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.2
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  fl_chart: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  quickalert: ^1.1.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-text.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo-text-2.png

  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/logo-text-2.png


flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/svg/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
